# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHHTufYj6ZmpbEdnfpj-A9WxSaLl2WfW
"""

class Library:
    def __init__(self):
        self.file = open("books.txt", "a+")

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        books = self.file.read().splitlines()
        for book in books:
            title, author, year, pages = book.split(',')
            print(f"Title: {title}, Author: {author}")

    def add_book(self):
        title = input("Enter the title of the book: ")
        author = input("Enter the author of the book: ")
        year = input("Enter the first release year: ")
        pages = input("Enter the number of pages: ")
        book_info = f"{title},{author},{year},{pages}\n"
        self.file.write(book_info)

    def remove_book(self):
        title = input("Enter the title of the book to remove: ")
        self.file.seek(0)
        books = self.file.read().splitlines()
        updated_books = [book for book in books if title not in book]
        self.file.seek(0)
        self.file.truncate()
        for book in updated_books:
            self.file.write(book + "\n")
    def exit_book(self):
        raise SystemExit()
lib = Library()

print("*** MENU***")
print("1) List Books")
print("2) Add Book")
print("3) Remove Book")
print("4)press q to exit")
menusec = 0
while menusec != 'q':
  menu_choice = input("Enter Your Chooice: ")
  if menu_choice == "1":
      lib.list_books()
  elif menu_choice == "2":
      lib.add_book()
  elif menu_choice == "3":
      lib.remove_book()
  elif menu_choice == "q":
      lib.exit_book()
  print("Invalid choice. Please select a valid option.")